# 第一阶段：构建前端
FROM node:18-alpine as builder

WORKDIR /frontend

# 复制依赖文件并安装依赖
COPY package*.json ./
RUN npm install

# 复制其余的应用代码
COPY . .

# 构建应用
RUN npm run build

# 第二阶段：使用 Nginx 提供静态文件
FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

# 复制构建好的文件到 Nginx 的默认目录
COPY --from=builder /frontend/dist /usr/share/nginx/html


EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]


